
(gautomatcher) D:\Users\Cthulhu\Documents\workspace\gautomatch-gui\ui_elements>python C:\Users\Cthulhu\Anaconda3\envs\gautomatcher\Library\bin\pyside2-uic main_window.ui 
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Thu May 10 17:28:59 2018
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1130, 961)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 40, 781, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.basicOptionsLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.basicOptionsLayout.setContentsMargins(0, 0, 0, 0)
        self.basicOptionsLayout.setObjectName("basicOptionsLayout")
        self.aPixTLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.aPixTLabel.setObjectName("aPixTLabel")
        self.basicOptionsLayout.addWidget(self.aPixTLabel, 1, 3, 1, 1)
        self.templateLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.templateLabel.setObjectName("templateLabel")
        self.basicOptionsLayout.addWidget(self.templateLabel, 1, 0, 1, 1)
        self.micrographsBrowseButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.micrographsBrowseButton.setObjectName("micrographsBrowseButton")
        self.basicOptionsLayout.addWidget(self.micrographsBrowseButton, 0, 2, 1, 1)
        self.templateBrowseButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.templateBrowseButton.setObjectName("templateBrowseButton")
        self.basicOptionsLayout.addWidget(self.templateBrowseButton, 1, 2, 1, 1)
        self.templatesBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.templatesBox.setObjectName("templatesBox")
        self.basicOptionsLayout.addWidget(self.templatesBox, 1, 1, 1, 1)
        self.micrographsBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.micrographsBox.setObjectName("micrographsBox")
        self.basicOptionsLayout.addWidget(self.micrographsBox, 0, 1, 1, 1)
        self.micrographsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.micrographsLabel.setObjectName("micrographsLabel")
        self.basicOptionsLayout.addWidget(self.micrographsLabel, 0, 0, 1, 1)
        self.aPixMLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.aPixMLabel.setObjectName("aPixMLabel")
        self.basicOptionsLayout.addWidget(self.aPixMLabel, 0, 3, 1, 1)
        self.diameterLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.diameterLabel.setObjectName("diameterLabel")
        self.basicOptionsLayout.addWidget(self.diameterLabel, 3, 3, 1, 1)
        self.aPixTBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.aPixTBox.setObjectName("aPixTBox")
        self.basicOptionsLayout.addWidget(self.aPixTBox, 1, 4, 1, 1)
        self.diameterBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.diameterBox.setObjectName("diameterBox")
        self.basicOptionsLayout.addWidget(self.diameterBox, 3, 4, 1, 1)
        self.aPixMBox = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.aPixMBox.setObjectName("aPixMBox")
        self.basicOptionsLayout.addWidget(self.aPixMBox, 0, 4, 1, 1)
        self.basicOptionsLabel = QtWidgets.QLabel(self.centralwidget)
        self.basicOptionsLabel.setGeometry(QtCore.QRect(0, 10, 71, 16))
        self.basicOptionsLabel.setObjectName("basicOptionsLabel")
        self.micrographWidget = QtWidgets.QWidget(self.centralwidget)
        self.micrographWidget.setGeometry(QtCore.QRect(0, 180, 781, 641))
        self.micrographWidget.setObjectName("micrographWidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 830, 301, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)
        self.runButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.resetButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1130, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.aPixTLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Å/pixel (templates)", None, -1))
        self.templateLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Templates", None, -1))
        self.micrographsBrowseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.templateBrowseButton.setText(QtWidgets.QApplication.translate("MainWindow", "Browse...", None, -1))
        self.micrographsLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Micrographs", None, -1))
        self.aPixMLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Å/pixel (micrograph)", None, -1))
        self.diameterLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Particle diameter (Å)", None, -1))
        self.basicOptionsLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Basic Options", None, -1))
        self.quitButton.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.runButton.setText(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.resetButton.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))

