# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Sun May 13 17:16:41 2018
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Gautomatcher(object):
    def setupUi(self, Gautomatcher):
        Gautomatcher.setObjectName("Gautomatcher")
        Gautomatcher.resize(1018, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Gautomatcher.sizePolicy().hasHeightForWidth())
        Gautomatcher.setSizePolicy(sizePolicy)
        Gautomatcher.setMinimumSize(QtCore.QSize(1000, 900))
        self.centralwidget = QtWidgets.QWidget(Gautomatcher)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(619, 830, 381, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.RestoreDefaults)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(320, 10, 551, 151))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.browseLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.browseLayout.setContentsMargins(0, 0, 0, 0)
        self.browseLayout.setObjectName("browseLayout")
        self.templatesBox = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templatesBox.sizePolicy().hasHeightForWidth())
        self.templatesBox.setSizePolicy(sizePolicy)
        self.templatesBox.setMinimumSize(QtCore.QSize(200, 20))
        self.templatesBox.setObjectName("templatesBox")
        self.browseLayout.addWidget(self.templatesBox, 2, 1, 1, 1)
        self.templateLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.templateLabel.sizePolicy().hasHeightForWidth())
        self.templateLabel.setSizePolicy(sizePolicy)
        self.templateLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.templateLabel.setObjectName("templateLabel")
        self.browseLayout.addWidget(self.templateLabel, 2, 0, 1, 1)
        self.micrographsBrowseButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micrographsBrowseButton.sizePolicy().hasHeightForWidth())
        self.micrographsBrowseButton.setSizePolicy(sizePolicy)
        self.micrographsBrowseButton.setMinimumSize(QtCore.QSize(0, 20))
        self.micrographsBrowseButton.setObjectName("micrographsBrowseButton")
        self.browseLayout.addWidget(self.micrographsBrowseButton, 1, 2, 1, 1)
        self.templateBrowseButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateBrowseButton.sizePolicy().hasHeightForWidth())
        self.templateBrowseButton.setSizePolicy(sizePolicy)
        self.templateBrowseButton.setMinimumSize(QtCore.QSize(0, 20))
        self.templateBrowseButton.setObjectName("templateBrowseButton")
        self.browseLayout.addWidget(self.templateBrowseButton, 2, 2, 1, 1)
        self.micrographsLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.micrographsLabel.sizePolicy().hasHeightForWidth())
        self.micrographsLabel.setSizePolicy(sizePolicy)
        self.micrographsLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.micrographsLabel.setObjectName("micrographsLabel")
        self.browseLayout.addWidget(self.micrographsLabel, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.browseLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.micrographsBox = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micrographsBox.sizePolicy().hasHeightForWidth())
        self.micrographsBox.setSizePolicy(sizePolicy)
        self.micrographsBox.setMinimumSize(QtCore.QSize(200, 20))
        self.micrographsBox.setObjectName("micrographsBox")
        self.browseLayout.addWidget(self.micrographsBox, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.browseLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.inputLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.inputLabel.sizePolicy().hasHeightForWidth())
        self.inputLabel.setSizePolicy(sizePolicy)
        self.inputLabel.setMinimumSize(QtCore.QSize(120, 45))
        self.inputLabel.setObjectName("inputLabel")
        self.browseLayout.addWidget(self.inputLabel, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 294, 839))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.optionsVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.optionsVLayout.setContentsMargins(0, 0, 0, 0)
        self.optionsVLayout.setObjectName("optionsVLayout")
        self.basicOptionsLayout = QtWidgets.QGridLayout()
        self.basicOptionsLayout.setObjectName("basicOptionsLayout")
        self.aPixTBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aPixTBox.sizePolicy().hasHeightForWidth())
        self.aPixTBox.setSizePolicy(sizePolicy)
        self.aPixTBox.setMinimumSize(QtCore.QSize(0, 20))
        self.aPixTBox.setObjectName("aPixTBox")
        self.basicOptionsLayout.addWidget(self.aPixTBox, 2, 2, 1, 1)
        self.aPixMBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aPixMBox.sizePolicy().hasHeightForWidth())
        self.aPixMBox.setSizePolicy(sizePolicy)
        self.aPixMBox.setMinimumSize(QtCore.QSize(0, 20))
        self.aPixMBox.setObjectName("aPixMBox")
        self.basicOptionsLayout.addWidget(self.aPixMBox, 1, 2, 1, 1)
        self.basicOptionsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.basicOptionsLabel.sizePolicy().hasHeightForWidth())
        self.basicOptionsLabel.setSizePolicy(sizePolicy)
        self.basicOptionsLabel.setMinimumSize(QtCore.QSize(120, 45))
        self.basicOptionsLabel.setObjectName("basicOptionsLabel")
        self.basicOptionsLayout.addWidget(self.basicOptionsLabel, 0, 0, 1, 1)
        self.aPixMLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aPixMLabel.sizePolicy().hasHeightForWidth())
        self.aPixMLabel.setSizePolicy(sizePolicy)
        self.aPixMLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.aPixMLabel.setObjectName("aPixMLabel")
        self.basicOptionsLayout.addWidget(self.aPixMLabel, 1, 0, 1, 1)
        self.aPixTLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aPixTLabel.sizePolicy().hasHeightForWidth())
        self.aPixTLabel.setSizePolicy(sizePolicy)
        self.aPixTLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.aPixTLabel.setObjectName("aPixTLabel")
        self.basicOptionsLayout.addWidget(self.aPixTLabel, 2, 0, 1, 1)
        self.diameterLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameterLabel.sizePolicy().hasHeightForWidth())
        self.diameterLabel.setSizePolicy(sizePolicy)
        self.diameterLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.diameterLabel.setObjectName("diameterLabel")
        self.basicOptionsLayout.addWidget(self.diameterLabel, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(23, 23, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.basicOptionsLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.diameterBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diameterBox.sizePolicy().hasHeightForWidth())
        self.diameterBox.setSizePolicy(sizePolicy)
        self.diameterBox.setMinimumSize(QtCore.QSize(49, 20))
        self.diameterBox.setMaximum(10000)
        self.diameterBox.setObjectName("diameterBox")
        self.basicOptionsLayout.addWidget(self.diameterBox, 3, 2, 1, 1)
        self.optionsVLayout.addLayout(self.basicOptionsLayout)
        self.additionalOptionsLayout = QtWidgets.QGridLayout()
        self.additionalOptionsLayout.setObjectName("additionalOptionsLayout")
        self.helpButtonMinDistance = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonMinDistance.sizePolicy().hasHeightForWidth())
        self.helpButtonMinDistance.setSizePolicy(sizePolicy)
        self.helpButtonMinDistance.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonMinDistance.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonMinDistance.setObjectName("helpButtonMinDistance")
        self.additionalOptionsLayout.addWidget(self.helpButtonMinDistance, 4, 1, 1, 1)
        self.helpButtonCcCutoff = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonCcCutoff.sizePolicy().hasHeightForWidth())
        self.helpButtonCcCutoff.setSizePolicy(sizePolicy)
        self.helpButtonCcCutoff.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonCcCutoff.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonCcCutoff.setObjectName("helpButtonCcCutoff")
        self.additionalOptionsLayout.addWidget(self.helpButtonCcCutoff, 5, 1, 1, 1)
        self.helpButtonSpeed = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonSpeed.sizePolicy().hasHeightForWidth())
        self.helpButtonSpeed.setSizePolicy(sizePolicy)
        self.helpButtonSpeed.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonSpeed.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonSpeed.setObjectName("helpButtonSpeed")
        self.additionalOptionsLayout.addWidget(self.helpButtonSpeed, 2, 1, 1, 1)
        self.speedBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedBox.sizePolicy().hasHeightForWidth())
        self.speedBox.setSizePolicy(sizePolicy)
        self.speedBox.setMinimumSize(QtCore.QSize(49, 20))
        self.speedBox.setMinimum(1)
        self.speedBox.setMaximum(4)
        self.speedBox.setObjectName("speedBox")
        self.additionalOptionsLayout.addWidget(self.speedBox, 2, 2, 1, 1)
        self.additionalOptionsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.additionalOptionsLabel.sizePolicy().hasHeightForWidth())
        self.additionalOptionsLabel.setSizePolicy(sizePolicy)
        self.additionalOptionsLabel.setMinimumSize(QtCore.QSize(120, 45))
        self.additionalOptionsLabel.setObjectName("additionalOptionsLabel")
        self.additionalOptionsLayout.addWidget(self.additionalOptionsLabel, 0, 0, 1, 1)
        self.boxSizeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSizeLabel.sizePolicy().hasHeightForWidth())
        self.boxSizeLabel.setSizePolicy(sizePolicy)
        self.boxSizeLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.boxSizeLabel.setObjectName("boxSizeLabel")
        self.additionalOptionsLayout.addWidget(self.boxSizeLabel, 3, 0, 1, 1)
        self.angStepBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angStepBox.sizePolicy().hasHeightForWidth())
        self.angStepBox.setSizePolicy(sizePolicy)
        self.angStepBox.setMinimumSize(QtCore.QSize(49, 20))
        self.angStepBox.setMaximum(360)
        self.angStepBox.setObjectName("angStepBox")
        self.additionalOptionsLayout.addWidget(self.angStepBox, 1, 2, 1, 1)
        self.angStepLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angStepLabel.sizePolicy().hasHeightForWidth())
        self.angStepLabel.setSizePolicy(sizePolicy)
        self.angStepLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.angStepLabel.setObjectName("angStepLabel")
        self.additionalOptionsLayout.addWidget(self.angStepLabel, 1, 0, 1, 1)
        self.speedLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedLabel.sizePolicy().hasHeightForWidth())
        self.speedLabel.setSizePolicy(sizePolicy)
        self.speedLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.speedLabel.setObjectName("speedLabel")
        self.additionalOptionsLayout.addWidget(self.speedLabel, 2, 0, 1, 1)
        self.ccCutoffLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccCutoffLabel.sizePolicy().hasHeightForWidth())
        self.ccCutoffLabel.setSizePolicy(sizePolicy)
        self.ccCutoffLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.ccCutoffLabel.setObjectName("ccCutoffLabel")
        self.additionalOptionsLayout.addWidget(self.ccCutoffLabel, 5, 0, 1, 1)
        self.helpButtonBoxSize = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonBoxSize.sizePolicy().hasHeightForWidth())
        self.helpButtonBoxSize.setSizePolicy(sizePolicy)
        self.helpButtonBoxSize.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonBoxSize.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonBoxSize.setObjectName("helpButtonBoxSize")
        self.additionalOptionsLayout.addWidget(self.helpButtonBoxSize, 3, 1, 1, 1)
        self.boxSizeBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxSizeBox.sizePolicy().hasHeightForWidth())
        self.boxSizeBox.setSizePolicy(sizePolicy)
        self.boxSizeBox.setMinimumSize(QtCore.QSize(49, 20))
        self.boxSizeBox.setMaximum(10000)
        self.boxSizeBox.setObjectName("boxSizeBox")
        self.additionalOptionsLayout.addWidget(self.boxSizeBox, 3, 2, 1, 1)
        self.minDistanceBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.minDistanceBox.setMinimumSize(QtCore.QSize(49, 0))
        self.minDistanceBox.setMaximum(10000)
        self.minDistanceBox.setObjectName("minDistanceBox")
        self.additionalOptionsLayout.addWidget(self.minDistanceBox, 4, 2, 1, 1)
        self.helpButtonAngStep = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonAngStep.sizePolicy().hasHeightForWidth())
        self.helpButtonAngStep.setSizePolicy(sizePolicy)
        self.helpButtonAngStep.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonAngStep.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonAngStep.setObjectName("helpButtonAngStep")
        self.additionalOptionsLayout.addWidget(self.helpButtonAngStep, 1, 1, 1, 1)
        self.minDistanceLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minDistanceLabel.sizePolicy().hasHeightForWidth())
        self.minDistanceLabel.setSizePolicy(sizePolicy)
        self.minDistanceLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.minDistanceLabel.setObjectName("minDistanceLabel")
        self.additionalOptionsLayout.addWidget(self.minDistanceLabel, 4, 0, 1, 1)
        self.ccCutoffBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.ccCutoffBox.setMinimumSize(QtCore.QSize(49, 0))
        self.ccCutoffBox.setObjectName("ccCutoffBox")
        self.additionalOptionsLayout.addWidget(self.ccCutoffBox, 5, 2, 1, 1)
        self.optionsVLayout.addLayout(self.additionalOptionsLayout)
        self.carbonLayout = QtWidgets.QGridLayout()
        self.carbonLayout.setObjectName("carbonLayout")
        self.carbonDetectionLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.carbonDetectionLabel.sizePolicy().hasHeightForWidth())
        self.carbonDetectionLabel.setSizePolicy(sizePolicy)
        self.carbonDetectionLabel.setMinimumSize(QtCore.QSize(120, 45))
        self.carbonDetectionLabel.setObjectName("carbonDetectionLabel")
        self.carbonLayout.addWidget(self.carbonDetectionLabel, 0, 0, 1, 1)
        self.localSigmaLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localSigmaLabel.sizePolicy().hasHeightForWidth())
        self.localSigmaLabel.setSizePolicy(sizePolicy)
        self.localSigmaLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.localSigmaLabel.setObjectName("localSigmaLabel")
        self.carbonLayout.addWidget(self.localSigmaLabel, 1, 0, 1, 1)
        self.localSigmaDiameterLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localSigmaDiameterLabel.sizePolicy().hasHeightForWidth())
        self.localSigmaDiameterLabel.setSizePolicy(sizePolicy)
        self.localSigmaDiameterLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.localSigmaDiameterLabel.setObjectName("localSigmaDiameterLabel")
        self.carbonLayout.addWidget(self.localSigmaDiameterLabel, 2, 0, 1, 1)
        self.localSigmaCutoffBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localSigmaCutoffBox.sizePolicy().hasHeightForWidth())
        self.localSigmaCutoffBox.setSizePolicy(sizePolicy)
        self.localSigmaCutoffBox.setMinimumSize(QtCore.QSize(0, 20))
        self.localSigmaCutoffBox.setMinimum(-99.0)
        self.localSigmaCutoffBox.setMaximum(99.0)
        self.localSigmaCutoffBox.setObjectName("localSigmaCutoffBox")
        self.carbonLayout.addWidget(self.localSigmaCutoffBox, 1, 2, 1, 1)
        self.localSigmaDiameterBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localSigmaDiameterBox.sizePolicy().hasHeightForWidth())
        self.localSigmaDiameterBox.setSizePolicy(sizePolicy)
        self.localSigmaDiameterBox.setMinimumSize(QtCore.QSize(49, 20))
        self.localSigmaDiameterBox.setMaximum(10000)
        self.localSigmaDiameterBox.setObjectName("localSigmaDiameterBox")
        self.carbonLayout.addWidget(self.localSigmaDiameterBox, 2, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(23, 23, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.carbonLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.optionsVLayout.addLayout(self.carbonLayout)
        self.iceLayout = QtWidgets.QGridLayout()
        self.iceLayout.setObjectName("iceLayout")
        self.localAverageMinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localAverageMinBox.sizePolicy().hasHeightForWidth())
        self.localAverageMinBox.setSizePolicy(sizePolicy)
        self.localAverageMinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.localAverageMinBox.setMinimum(-99.0)
        self.localAverageMinBox.setObjectName("localAverageMinBox")
        self.iceLayout.addWidget(self.localAverageMinBox, 1, 2, 1, 1)
        self.helpButtonPreLowPass = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonPreLowPass.sizePolicy().hasHeightForWidth())
        self.helpButtonPreLowPass.setSizePolicy(sizePolicy)
        self.helpButtonPreLowPass.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonPreLowPass.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonPreLowPass.setObjectName("helpButtonPreLowPass")
        self.iceLayout.addWidget(self.helpButtonPreLowPass, 6, 1, 1, 1)
        self.helpButtonPreHighPass = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonPreHighPass.sizePolicy().hasHeightForWidth())
        self.helpButtonPreHighPass.setSizePolicy(sizePolicy)
        self.helpButtonPreHighPass.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonPreHighPass.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonPreHighPass.setObjectName("helpButtonPreHighPass")
        self.iceLayout.addWidget(self.helpButtonPreHighPass, 7, 1, 1, 1)
        self.preLowPassLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preLowPassLabel.sizePolicy().hasHeightForWidth())
        self.preLowPassLabel.setSizePolicy(sizePolicy)
        self.preLowPassLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.preLowPassLabel.setObjectName("preLowPassLabel")
        self.iceLayout.addWidget(self.preLowPassLabel, 6, 0, 1, 1)
        self.preHighPassLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preHighPassLabel.sizePolicy().hasHeightForWidth())
        self.preHighPassLabel.setSizePolicy(sizePolicy)
        self.preHighPassLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.preHighPassLabel.setObjectName("preHighPassLabel")
        self.iceLayout.addWidget(self.preHighPassLabel, 7, 0, 1, 1)
        self.localAverageMaxBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localAverageMaxBox.sizePolicy().hasHeightForWidth())
        self.localAverageMaxBox.setSizePolicy(sizePolicy)
        self.localAverageMaxBox.setMinimumSize(QtCore.QSize(0, 20))
        self.localAverageMaxBox.setObjectName("localAverageMaxBox")
        self.iceLayout.addWidget(self.localAverageMaxBox, 2, 2, 1, 1)
        self.iceLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.iceLabel.sizePolicy().hasHeightForWidth())
        self.iceLabel.setSizePolicy(sizePolicy)
        self.iceLabel.setMinimumSize(QtCore.QSize(120, 45))
        self.iceLabel.setObjectName("iceLabel")
        self.iceLayout.addWidget(self.iceLabel, 0, 0, 1, 1)
        self.localAverageMinLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localAverageMinLabel.sizePolicy().hasHeightForWidth())
        self.localAverageMinLabel.setSizePolicy(sizePolicy)
        self.localAverageMinLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.localAverageMinLabel.setObjectName("localAverageMinLabel")
        self.iceLayout.addWidget(self.localAverageMinLabel, 1, 0, 1, 1)
        self.localAverageMaxLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localAverageMaxLabel.sizePolicy().hasHeightForWidth())
        self.localAverageMaxLabel.setSizePolicy(sizePolicy)
        self.localAverageMaxLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.localAverageMaxLabel.setObjectName("localAverageMaxLabel")
        self.iceLayout.addWidget(self.localAverageMaxLabel, 2, 0, 1, 1)
        self.highPassLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highPassLabel.sizePolicy().hasHeightForWidth())
        self.highPassLabel.setSizePolicy(sizePolicy)
        self.highPassLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.highPassLabel.setObjectName("highPassLabel")
        self.iceLayout.addWidget(self.highPassLabel, 5, 0, 1, 1)
        self.localAverageDiameterLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localAverageDiameterLabel.sizePolicy().hasHeightForWidth())
        self.localAverageDiameterLabel.setSizePolicy(sizePolicy)
        self.localAverageDiameterLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.localAverageDiameterLabel.setObjectName("localAverageDiameterLabel")
        self.iceLayout.addWidget(self.localAverageDiameterLabel, 3, 0, 1, 1)
        self.lowPassBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowPassBox.sizePolicy().hasHeightForWidth())
        self.lowPassBox.setSizePolicy(sizePolicy)
        self.lowPassBox.setMinimumSize(QtCore.QSize(49, 20))
        self.lowPassBox.setMaximum(10000)
        self.lowPassBox.setObjectName("lowPassBox")
        self.iceLayout.addWidget(self.lowPassBox, 4, 2, 1, 1)
        self.localAverageDiameterBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.localAverageDiameterBox.sizePolicy().hasHeightForWidth())
        self.localAverageDiameterBox.setSizePolicy(sizePolicy)
        self.localAverageDiameterBox.setMinimumSize(QtCore.QSize(49, 20))
        self.localAverageDiameterBox.setMaximum(10000)
        self.localAverageDiameterBox.setObjectName("localAverageDiameterBox")
        self.iceLayout.addWidget(self.localAverageDiameterBox, 3, 2, 1, 1)
        self.lowPassLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowPassLabel.sizePolicy().hasHeightForWidth())
        self.lowPassLabel.setSizePolicy(sizePolicy)
        self.lowPassLabel.setMinimumSize(QtCore.QSize(120, 30))
        self.lowPassLabel.setObjectName("lowPassLabel")
        self.iceLayout.addWidget(self.lowPassLabel, 4, 0, 1, 1)
        self.helpButtonlocalAverageMax = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonlocalAverageMax.sizePolicy().hasHeightForWidth())
        self.helpButtonlocalAverageMax.setSizePolicy(sizePolicy)
        self.helpButtonlocalAverageMax.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonlocalAverageMax.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonlocalAverageMax.setObjectName("helpButtonlocalAverageMax")
        self.iceLayout.addWidget(self.helpButtonlocalAverageMax, 2, 1, 1, 1)
        self.helpButtonHighPass = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonHighPass.sizePolicy().hasHeightForWidth())
        self.helpButtonHighPass.setSizePolicy(sizePolicy)
        self.helpButtonHighPass.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonHighPass.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonHighPass.setObjectName("helpButtonHighPass")
        self.iceLayout.addWidget(self.helpButtonHighPass, 5, 1, 1, 1)
        self.helpButtonLowPass = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonLowPass.sizePolicy().hasHeightForWidth())
        self.helpButtonLowPass.setSizePolicy(sizePolicy)
        self.helpButtonLowPass.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonLowPass.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonLowPass.setObjectName("helpButtonLowPass")
        self.iceLayout.addWidget(self.helpButtonLowPass, 4, 1, 1, 1)
        self.helpButtonLocalAverageDiameter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonLocalAverageDiameter.sizePolicy().hasHeightForWidth())
        self.helpButtonLocalAverageDiameter.setSizePolicy(sizePolicy)
        self.helpButtonLocalAverageDiameter.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonLocalAverageDiameter.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonLocalAverageDiameter.setObjectName("helpButtonLocalAverageDiameter")
        self.iceLayout.addWidget(self.helpButtonLocalAverageDiameter, 3, 1, 1, 1)
        self.helpButtonlocalAverageMin = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButtonlocalAverageMin.sizePolicy().hasHeightForWidth())
        self.helpButtonlocalAverageMin.setSizePolicy(sizePolicy)
        self.helpButtonlocalAverageMin.setMinimumSize(QtCore.QSize(0, 0))
        self.helpButtonlocalAverageMin.setMaximumSize(QtCore.QSize(23, 23))
        self.helpButtonlocalAverageMin.setObjectName("helpButtonlocalAverageMin")
        self.iceLayout.addWidget(self.helpButtonlocalAverageMin, 1, 1, 1, 1)
        self.highPassBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.highPassBox.sizePolicy().hasHeightForWidth())
        self.highPassBox.setSizePolicy(sizePolicy)
        self.highPassBox.setMinimumSize(QtCore.QSize(49, 20))
        self.highPassBox.setMaximum(10000)
        self.highPassBox.setObjectName("highPassBox")
        self.iceLayout.addWidget(self.highPassBox, 5, 2, 1, 1)
        self.preLowPassBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preLowPassBox.sizePolicy().hasHeightForWidth())
        self.preLowPassBox.setSizePolicy(sizePolicy)
        self.preLowPassBox.setMinimumSize(QtCore.QSize(49, 20))
        self.preLowPassBox.setMaximum(10000)
        self.preLowPassBox.setObjectName("preLowPassBox")
        self.iceLayout.addWidget(self.preLowPassBox, 6, 2, 1, 1)
        self.preHighPassBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preHighPassBox.sizePolicy().hasHeightForWidth())
        self.preHighPassBox.setSizePolicy(sizePolicy)
        self.preHighPassBox.setMinimumSize(QtCore.QSize(49, 20))
        self.preHighPassBox.setMaximum(10000)
        self.preHighPassBox.setObjectName("preHighPassBox")
        self.iceLayout.addWidget(self.preHighPassBox, 7, 2, 1, 1)
        self.optionsVLayout.addLayout(self.iceLayout)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(320, 170, 640, 640))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(640, 640))
        self.widget.setObjectName("widget")
        Gautomatcher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Gautomatcher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 21))
        self.menubar.setObjectName("menubar")
        Gautomatcher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Gautomatcher)
        self.statusbar.setObjectName("statusbar")
        Gautomatcher.setStatusBar(self.statusbar)

        self.retranslateUi(Gautomatcher)
        QtCore.QMetaObject.connectSlotsByName(Gautomatcher)

    def retranslateUi(self, Gautomatcher):
        Gautomatcher.setWindowTitle(QtWidgets.QApplication.translate("Gautomatcher", "MainWindow", None, -1))
        self.templateLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Templates", None, -1))
        self.micrographsBrowseButton.setText(QtWidgets.QApplication.translate("Gautomatcher", "Browse...", None, -1))
        self.templateBrowseButton.setText(QtWidgets.QApplication.translate("Gautomatcher", "Browse...", None, -1))
        self.micrographsLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Micrographs", None, -1))
        self.inputLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "<html><head/><body><p><span style=\" font-weight:600;\">Input</span></p></body></html>", None, -1))
        self.basicOptionsLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "<b>Basic Options</b>", None, -1))
        self.aPixMLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Å/pixel (micrographs)", None, -1))
        self.aPixTLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Å/pixel (templates)", None, -1))
        self.diameterLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Particle diameter (Å)", None, -1))
        self.helpButtonMinDistance.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonCcCutoff.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonSpeed.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.additionalOptionsLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "<b>Additional options</b>", None, -1))
        self.boxSizeLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Box size", None, -1))
        self.angStepLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Angular step", None, -1))
        self.speedLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Speed", None, -1))
        self.ccCutoffLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Cc cutoff", None, -1))
        self.helpButtonBoxSize.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonAngStep.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.minDistanceLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Minimum distance", None, -1))
        self.carbonDetectionLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "<b>Carbon detection</b>", None, -1))
        self.localSigmaLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Local σ cutoff", None, -1))
        self.localSigmaDiameterLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Local sigma diameter", None, -1))
        self.helpButtonPreLowPass.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonPreHighPass.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.preLowPassLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Pre low pass (Å)", None, -1))
        self.preHighPassLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Pre high pass (Å)", None, -1))
        self.iceLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "<b>Ice options</b>", None, -1))
        self.localAverageMinLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Local average min", None, -1))
        self.localAverageMaxLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Local average max", None, -1))
        self.highPassLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "High pass (Å)", None, -1))
        self.localAverageDiameterLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Local average diameter", None, -1))
        self.lowPassLabel.setText(QtWidgets.QApplication.translate("Gautomatcher", "Low pass (Å)", None, -1))
        self.helpButtonlocalAverageMax.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonHighPass.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonLowPass.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonLocalAverageDiameter.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))
        self.helpButtonlocalAverageMin.setText(QtWidgets.QApplication.translate("Gautomatcher", "?", None, -1))

